### PR TITLE
Filters for output of opening and closing of #main div

### PR DESCRIPTION
**Pull request by vanpop**
Any reason not to do this?

### CODE REVIEW

**Comment by falcoraptor** [comment]
No, not really. What is your use case for having them? Would you like to be able to remove the div, or is it for changing css classes?

**Comment by JamesGeiger** [comment]
I don't think you would ever need to change this....

**Comment by vanpop** [comment]
I've used it to change classes specifically for mashing up thematic and bootstrap.

**Comment by JamesGeiger** [comment]
Oh...well that makes sense :). I just never use bootstrap because I roll my own SASS and Compass.

**Comment by falcoraptor** [comment]
@vanpop Would you like to have filters on `#container` as well, or is the `#main` div enough for your uses?

**Comment by falcoraptor** [comment]
Sorry, mouse-slip.

**Comment by vanpop** [comment]
I noticed I was missing a few characters at the bottom of that last commit (so much for my quick editing on GitHub). Anyhow, I corrected that and I also added filters for the #container open and close, and also for the #content close. Filter all the things? No?

**Comment by falcoraptor** [comment]
Well yes why not? We discussed it a bit before when I added the header and footer filters for my html5 plugin to work. I had a hard time to read the diff's because of all the whitespace changes so I had to check out the code to have a look at it. It looks cleaner not to jump in and out of html all the time.

I think you missed the links.php file. Add that and I'll pull the branch.

**Comment by vanpop** [comment]
Ah! not sure how I missed that. links.php is done, and I also added filters for the closing head, body, and html tags. Even though it is unnecessary, I figured it would make more sense to provide the ability for any unforeseen (unimaginable/unnecessary) cases while I was in filter-all-the-things mode.

**Comment by falcoraptor** [comment]
Haha, well I don't know if anyone would ever need to filter the closing html tag. :) 
If @emhr disapproves, we can reverse it, but I will pull this branch in the meantime. 
Thanks for your contribution!

**Pull request merged**
