### PR TITLE
Add sample childtheme setup to the sample child theme

### PR DESCRIPTION
**Pull request by falcoraptor**
Add theme support for custom background and custom headers.
Re #13

### CODE REVIEW

**Comment by falcoraptor** [comment]
@helgatheviking Have a look. I tested it a little bit and it works with the theme customizer. I put it on the after_setup_theme hook, but it could be attached to thematic_child_init as well.

**Comment by helgatheviking** [comment]
i like.  do you think there is any reason to attach it to thematic_child_init() ??  it isn't really interacting w/ thematic.  

all seems to work for me.  i only am just now thinking about how much of this 'customizer' stuff we should be putting in the free version and what we'd want to hang on to for a premium plugin.

**Comment by falcoraptor** [comment]
Well it's the same place/hook in reality. I was just thinking of making people aware that it exists. Though I'm not too clear on why it exists myself so I guess it doesn't really matter.

Well I think putting theme options into the customizer is one thing. Using the built-in custom background and custom header is another since it shows up in the customizer automatically. The only candidate for the customizer would be the footer text as it is now anyway. I think it would be fair to leave it up to the child themes.

**Comment by helgatheviking** [comment]
i don't totally know why it is there either... maybe it the best place to
remove thematic functions?  except that i usually just use init, which
comes after that anyway.

pulled.  is there anything else we are waiting on for 1.0.3.

**Pull request merged**
