### PR TITLE
Localization revamp

### PR DESCRIPTION
**Pull request by falcoraptor**
Making a pull request so we have an issue to discuss in.

### CODE REVIEW

**Comment by helgatheviking** [comment]
ok.  i don't think it is ready to be pulled into anything, but its good we can discuss it this way.  i tried to follow otto's advice and make everything into whole phrases.  it was harder in some places, b/c thematic seems to have extra markup inserted into said phrases.

**Comment by falcoraptor** [comment]
Well definitely not, I just wanted to create the issue for us to discuss in. I also did a runthrough of content-extensions, I will need to dig it out and see what we made different. I also went through comments.php and comments-extensions.php but that is as far as I got.

One thing I saw though is that spaces need to be outside of the string but punctuation needs to be _inside_. This is to enable proper punctuation in RTL languages - and now that we have hebrew we need to consider that too.

**Comment by helgatheviking** [comment]
gotcha.  punctuation goes inside.  makes sense.  do you think it is worth removing the html markup from the strings as much as possible?  if somebody wants an extra span/em/strong can't they filter it in themselves?

**Comment by falcoraptor** [comment]
I think that the em's and strong's should be included, since they might need to be moved around in different languages. The span's i guess depends on context. One or two html tags won't hurt anyone though.

**Comment by helgatheviking** [comment]
good reminder.  sometimes i like overkill.

**Comment by helgatheviking** [comment]
why is this a string? (comments-extensions.php)
`__('<span class="required">*</span>', 'thematic')`

**Comment by helgatheviking** [comment]
in the thematic_widgetized_areas function

```
'Primary Aside' => array(
            'admin_menu_order' => 100,
            'args' => array (
                'name' => 'Primary Aside',
                'id' => 'primary-aside',
                'description' => __('The primary widget area, most often used as a sidebar.', 'thematic'),
                'before_widget' => thematic_before_widget(),
                'after_widget' => thematic_after_widget(),
                'before_title' => thematic_before_title(),
                'after_title' => thematic_after_title(),
                ),
            'action_hook'   => 'widget_area_primary_aside',
            'function'      => 'thematic_primary_aside',
            'priority'      => 10,
            ),
```

should the 'name' argument be translated?  I think yes.

**Comment by falcoraptor** [comment]
there is  `__(thematic_commentbox_text(), 'thematic')` in thematic_commentform_args and then we have

```
function thematic_commentbox_text() {
    $content = __('Comment', 'thematic');
    return apply_filters( 'thematic_commentbox_text', $content );
}
```

which seems a bit redundant. I think simply a call thematic_commentbox_text() is enough

**Comment by helgatheviking** [comment]
I saw that somewhere else and thought the same thing.  must've missed this one.  totally agree, go ahead and fix that.  we already have enough code without working for the department of redundancy department

**Comment by falcoraptor** [comment]
I think i put the target wrong. Will make a new one targetting dev instead of master

**Pull request closed without merging**
