### PR TITLE
Fix L10n function call in library/extensions/comments-extensions.php

### PR DESCRIPTION
**Pull request by ghost**
Hi there,

I have fixed a localization function call that was preventing the translation of the string "Trackbacks are closed, but you can %1$spost a comment%2$s." from being displayed (note: this string is displayed when trackbacks are disabled, but comments are open).

However, my fix does not cause the translation string to appear, because I the PO and MO files also have to be updated to include the context information (for example in the French locale, the fr_FR.po file is missing the message context information on line 329 - compare with line 324). Therefore I believe that the POT file should also be updated, reimported into Glotpress, and then that all PO and MO language files should be regenerated from there.

I hope this helps. Please let me know if I can be of any help with this.

Best,

Florent

### CODE REVIEW

**Comment by falcoraptor** [comment]
Thanks polnoft, good catch!

@emhr Gene, is it ok if I go ahead and merge this? I can regenerate POT and upload to glotpress too.

**Comment by ghost** [comment]
Yep! Go for it on the merge and regeneration. Please close the ticket when its complete. Thanks!

**Comment by falcoraptor** [comment]
Done! 
I reimported the POT into glotpress, so translators can go ahead an update their translations now. 
It would be great if there was some way to contact all translators, like a mailinglist, for situations like these. It's only two strings so it would only take them a second to do it, and it would increase the number of complete translations that gets included in the releases.

**Comment by ghost** [comment]
Thanks Middlesister!
I've updated the French translation. A tad disappointed that a string that was already translated has to be re-translated just because the function calling it changed from __() to _x()... Anyway, I guess that is a Glotpress issue, just ranting ;)
Glad I could help!

**Pull request merged**
