### PR TITLE
Deprecate all constants

### PR DESCRIPTION
**Pull request by helgatheviking**
i'm almost there.  i think the only constants left for me to deprecate are THEMATIC_COMPATIBLE_COMMENT_FORM and THEMATIC_COMPATIBLE_COMMENT_HANDLING

### CODE REVIEW

**Comment by helgatheviking** [comment]
should the dynamic class functions be moved to the deprecated file?

**Comment by falcoraptor** [comment]
The arguments to _deprecated_function() are already sprintf'd into a string by wordpress, so it looks weird to have a sentence within a sentence.

**Comment by helgatheviking** [comment]
but how are they translated like that?

**Comment by helgatheviking** [comment]
nm.  i see that it isn't supposed to be a message, but just the name of the replacement function.  i'm going to pull this into dev.  i think it is good enough for that.  and that still gives us time to catch anything major.

**Comment by falcoraptor** [comment]
`sprintf( __('%1$s is <strong>deprecated</strong> since version %2$s! Use %3$s instead.'), $function, $version, $replacement )`

Yes I think it's good enough. Good work.

**Pull request merged**
