### PR TITLE
Feature/mobile navigation

### PR DESCRIPTION
**Pull request by falcoraptor**
See #57
At the time of writing, this branch is active on http://thematicdev.invistruct.com for testing on mobile devices

### CODE REVIEW

**Comment by JamesGeiger** [comment]
@middlesister I have looked at this and it is perfect. 

Will it be filterable? (e.g. if a user wants to change the name to Nav or something).

**Comment by falcoraptor** [comment]
Is what filterable? What element are you referring too?

**Comment by falcoraptor** [comment]
Ah sorry, you mean the text for the menu button?
Of course it should be, I'll add that. I think it need to be localized too.

**Comment by JamesGeiger** [comment]
Yep, I meant the text for the menu button :)

**Comment by falcoraptor** [comment]
Done! Merging this.

**Comment by JamesGeiger** [comment]
@middlesister  Cool. You are doing such a great job, I am loving Thematic 2.0 :)

**Pull request merged**
