### PR TITLE
Update library/languages/pl_PL.po

### PR DESCRIPTION
**Pull request by hubert-jedrzejek**
Updated translation

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the updated Polish localization! 

Thematic is now using GlotPress to maintain it's localization files. It would be great if you could help update the Polish strings in our GlotPress database. 

To help out:
1. Sign up for an account here: http://thematictheme.com/wp-signup.php
2. Then log in here: http://translate.thematictheme.com/projects
3. Find the "active" project for the thematic framework 1.0.3.x at the time of my posting this.
4. Edit the strings

**Comment by ghost** [comment]
I'm not sure if this po file is in sync with thematic's current pot it seems to be missing a few strings. Such as the "(Untitled)" string for posts without titles.

**Comment by falcoraptor** [comment]
It is based on the previous pot file. The "(Untitled)" string was added just the other day together with polnoft's string fix. 

@hubert-jedrzejek Thanks for helping out! I saw you have updated the strings in glotpress. The are in waiting status and need to be approved by a validator, but we are currently missing a validator for polish. Would you like to be one? I can add you as a validator, just tell me you username. After the strings are marked as approved, the translation is finished and will be included in the next release.

**Comment by hubert-jedrzejek** [comment]
Sure, I can be a validator for polish translation. My login is:
hubertjedrzejek.

2012/12/16 Karin Taliga notifications@github.com

> It is based on the previous pot file. The "(Untitled)" string was added
> just the other day together with polnoft's string fix.
> 
> @hubert-jedrzejek https://github.com/hubert-jedrzejek Thanks for
> helping out! I saw you have updated the strings in glotpress. The are in
> waiting status and need to be approved by a validator, but we are currently
> missing a validator for polish. Would you like to be one? I can add you as
> a validator, just tell me you username. After the strings are marked as
> approved, the translation is finished and will be included in the next
> release.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ThematicTheme/Thematic/pull/24#issuecomment-11415694.

## 

Hubert Jędrzejek

**Comment by ghost** [comment]
Awesome, you're a validator now

**Comment by falcoraptor** [comment]
Great!

**Comment by falcoraptor** [comment]
Closing this since we now have the latest translation in Glotpress.

**Comment by ghost** [comment]
@hubert-jedrzejek  All you need to do now is log in to translate.thematictheme.com and "approve" or "reject" strings. Click on a string and look for this:

Untitled-2

**Pull request closed without merging**
