### PR TITLE
Localization revamp - include punctuation in strings

### PR DESCRIPTION
**Pull request by falcoraptor**

### CODE REVIEW

**Comment by helgatheviking** [comment]
great!!  i love the translators notes, but why are they in the function and not in the .pot file?

the translator shouldn't have to go look stuff up.  from what i've seen of poedit it doesn't really tell you where the string comes from.  plus there is a built in function _x()

so shouldn't :
`/* translators: comment reply form title, %s is author of comment */
     $content = __('Post a Reply to %s', 'thematic');`

be

  `$content = _x('Post a Reply to %s', 'comment reply form title, %s is author of comment', 'thematic');`

**Comment by falcoraptor** [comment]
I haven't regenerated the pot, so I don't know. In glotpress, both the _x context and the /\* comment */ shows, but differently. Look for example at
http://translate.wordpress.org/projects/wp/3.4.x/sv/default?filters[term]=&filters[user_login]=&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[with_comment]=yes&filters[with_context]=yes&filter=Filter&sort[by]=priority&sort[how]=desc
open the bottom "%1$s on %2$s"

Don't know how to put it in the pot, will have to google a bit here...

**Comment by helgatheviking** [comment]
i thought poedit sorted that automagically, but i just opened the .pot and no such luck.  <is stumped>

**Comment by falcoraptor** [comment]
There has to be some way to make poedit generate them. In wordpress own pot file it looks like this:

```
#. translators: column name in revisions

#: wp-includes/post-template.php:1419
msgctxt "revisions column name"
msgid "Old"
msgstr ""

```

So somehow, somewhere there is a possibility for getting the comments in. A setting or keyword or something like that. If worst comes to worst, we might have to resort to the command line (ugh).

**Comment by helgatheviking** [comment]
http://wp.tutsplus.com/tutorials/theme-development/translating-your-theme/

provided this:
- __
- _e
- _n:1,2
- _x:1,2c
- _ex:1,2c

The :1,2 extension tell POEdit that these keywords have two parts to them.
By default, the second argument is the plural unless you include the c which
mean the second argument is a comment.

but i still couldn't get the comments.  maybe a question for otto?  i will
leave you in charge of this!  :)  (don't want you to miss out on the fun)

On Sun, Jul 29, 2012 at 9:54 AM, Karin Taliga <
reply@reply.github.com

**Comment by falcoraptor** [comment]
Woot! I did it!

So it involved checking out http://svn.automattic.com/wordpress-i18n/tools/trunk/ and running the provided makepot.php file as per the bottom of http://codex.wordpress.org/I18n_for_WordPress_Developers

Command line:
`php makepot.php wp-theme path-to-thematic`

Both `msgctxt` and `#. translators`notes are in the file. But for some reason they don't show in poedit. I will try importing the pot into a new glotpress project and see if they show up

**Comment by falcoraptor** [comment]
Sooo, in glotpress they show. One more reason to use that I suppose. 
Check out http://translate.thematictheme.com/projects/thematic-framework/thematic-103/sv/default, I loaded the existing swedish po file. Time to load up the rest and let peopla hack away?
We can always regenerate pot and re-upload if we find more things...

**Comment by helgatheviking** [comment]
sweet! i knew there was a reason you were in charge of that.  :) so do you
think we're ready for a call to translators?  i guess we're more likely to
find errors as more translators look at it.  do you want to post a short
blog and in the forums?  they're supposed to use glotpress?  they can still
submit a pull to dev if they'd like too right?

can you push the new .pot into this branch?  explain how glotpress works again?

**Comment by falcoraptor** [comment]
Why not?
I just loaded all the previous language files into 1.0.3 so I think we are good to go there. We have changed almost half of the strings lol!
I have to make dinner now but I can make a post about it. Preferably glotpress but sure, people can make pull requests and we will have to upload the new files to glotpress ourselves...

**Comment by helgatheviking** [comment]
eww.. upload to glotpress ourselves?  i dislike extra work.  so when people
do stuff on glotpress it automatically updates the .po and .mo files for
their respective language?

full steam ahead.

there's a new bug that just popped up.  i'll try to deal w/ it at some
point... we can let the translators try to update some stuff and then we
can push out 1.0.3?  though i didn't hear from ian about our mini update
earlier in the week.  1.0.2.3 or whatever it was.  i hope he didn't just
ignore it since it was me and not either chris or gene emailing him an
update.

i need to come up with an email to him about thematic5 as an in-house theme.

On Sun, Jul 29, 2012 at 11:05 AM, Karin Taliga <
reply@reply.github.com

**Comment by helgatheviking** [comment]
i've merged this into dev.  (i hope).  :)  one thing though, the potfile has the following:

"Last-Translator: FULL NAME EMAIL@ADDRESS\n"
"Language-Team: LANGUAGE LL@li.org\n"

which should either be removed or filled out.  also supposedly poedit 1.5 handles comments now?  so i was informed by poedit on twitter, but i haven't figured it out yet either.

**Comment by falcoraptor** [comment]
Yes like I said in the email, I was not happy with the pot-file headers. I thought I would merge all the commits except the pot-file but you managed to get before me and merge the lot. :) never mind that, it's all in development anyway.

I will have to check out version 1.5...

**Comment by helgatheviking** [comment]
yeah hopefully you will have better luck.  i still couldn't process the comments.  probably shouldn't have merged it all, but as long as it is in dev i think we're ok!

**Pull request merged**
